### PR TITLE
665 is not close to

### LINKED ISSUE #665: Add isNotCloseTo
#### Summary

Check that a number is not close to another one by the given margin.

#### Example

```java
assertThat(1.0).isNotCloseTo(1.5, byLessThan(0.1));
```

#### Java 8 specific ?

NO : Pull Request must be based on the 2.x` branch.

### PR DESCRIPTION
**Pull request by ChrisA89**
#### Check List:
* Fixes #665 
* Unit tests : YES
* Javadoc with a code example (API only) : YES

### CODE REVIEW

**Comment by ChrisA89** [comment]
I've also made some minor fixes to the isCloseTo docs, which are rolled up in this PR, but are in a separate commit, so could be cherry-picked if needs be.

**Comment by joel-costigliola** [comment]
Thanks Chris, can you create the PR on the 2.x branch as there is nothing specific to java 8 (master = 2.x + java 8  stuff) ?

**Comment by ChrisA89** [comment]
Yes I can. I'd branched off the 2.x branch but created the PR in the wrong place.
I'll fix up the failed test too.

**Comment by joel-costigliola** [comment]
:+1:

**Pull request closed without merging**
