### PR TITLE
Align javadoc CSS to java 12 default, add CSS minification

### LINKED ISSUE #1570: Javadoc anchor links don't work (Java 11)
#### Summary

This works : https://static.javadoc.io/org.assertj/assertj-core/3.13.1/org/assertj/core/api/AbstractInstantAssert.html

This works when the link is clicked from the page: https://static.javadoc.io/org.assertj/assertj-core/3.13.1/org/assertj/core/api/AbstractInstantAssert.html#method.summary but open the same link in a new tab and it won't show the method summary, just the beginning of the page https://static.javadoc.io/org.assertj/assertj-core/3.13.1/org/assertj/core/api/AbstractInstantAssert.html

This is pretty annoying when you want to share a link to a specific section of a page.

### PR DESCRIPTION
**Pull request by scordio**
Should hopefully fix #1570!

Also bumped `highlight.js` to version 9.15.10.

### CODE REVIEW

**Comment by joel-costigliola** [comment]
Wow, how did find what the cause was ?

**Comment by joel-costigliola** [comment]
I'm merging it and generate the javadoc when I'll get back home to see if it fixes the issue, thanks!

**Comment by scordio** [comment]
> Wow, how did find what the cause was ?

I stumbled upon [this page](https://openjdk.java.net/jeps/225) and I started to play with the maven plugin, discovering that without the stylesheet parameter it was able to generate the default stylesheet of the jdk. 

Then I assumed our CSS has no customization except for highlight.js, so I combined the one from the JDK and the default from highlight.js! :-)

**Comment by joel-costigliola** [comment]
The links work now :) but the CSS is kinda lost so no code highlighted likely due to that warning when I'm generating the javadoc:
```
[INFO] --- maven-javadoc-plugin:3.1.1:javadoc (default-cli) @ assertj-core ---
[WARNING] Unable to find the resource 'home/joel/prog/assertj/assertj-core-3.x/target/javadoc-stylesheet/assertj-javadoc-min.css'. Using default Javadoc resources.
```

**Comment by scordio** [comment]
I might know why, I'll check soon

**Comment by scordio** [comment]
@joel-costigliola just pushed the maven phase fix, could you try again?

**Comment by joel-costigliola** [comment]
It works, awesome!
I just need to put back the railcast theme for highlight and we good.

**Comment by scordio** [comment]
Oh sorry I missed that.

**Comment by joel-costigliola** [comment]
Done!

**Comment by joel-costigliola** [comment]
will be 100% done when https://github.com/joel-costigliola/assertj-core/issues/1584 is addressed (but nothing urgent)

**Pull request merged**
