### PR TITLE
Add map, flatMap and extractingValue to OptionalAssert (#751, #748)

### LINKED ISSUE #751: Add map(…) and flatMap(…) to OptionalAssert
#### Summary

If you're dealing with `Optional`s whose values return `Optional`s, you end u with a lot of nesting. It would be cool if these could be flattened out like this:

#### Example

```java
Optiona<Foo> foo = Optional.of(foo);

assertThat(foo).hasValueSatisfying(it -> {
  assertThat(it.methodReturningAnOptional()).hasValueSatisfying(inner -> {
    assertThat(inner.methodReturningNoOptional()).isEqualTo(reference);
  }
}
```

Note, how you constantly have to nest expressions and also rewrap the values obtained from the method call into new asserts.

It would be cool if one could rather write this instead:

```java
assertThat(foo)
  .flatMap(it -> it.methodReturningAnOptional())
  .map(it -> it.methodReturningNoOptional())
  .isEqualTo(reference);
```

I currently have this custom assert class in my code to achieve this:

```java
public class OptionalAssert<T> extends AbstractAssert<OptionalAssert<T>, Optional<T>> {

  public OptionalAssert(Optional<T> actual) {
    super(actual, OptionalAssert.class);
  }

  public static <T> OptionalAssert<T> optionalAssertThat(Optional<T> optional) {
    return new OptionalAssert<T>(optional);
  }

  public <S> OptionalAssert<S> flatMap(Function<T, Optional<S>> function) {

    Assertions.assertThat(actual).isPresent();

    return optionalAssertThat(actual.flatMap(function));
  }

  public <S> AbstractObjectAssert<?, S> map(Function<T, S> function) {

    Assertions.assertThat(actual).isPresent();

    return Assertions.assertThat(actual.map(function).orElseThrow(() -> new IllegalStateException()));
  }
}
```

I guess that can be improved to report good error messages in case of a flat map step producing an empty `Optional`, but it does the trick for me now.

### PR DESCRIPTION
**Pull request by fiery-phoenix**
#### Check List:
* Fixes #751, #748
* Unit tests : YES
* Javadoc with a code example (API only) : YES

### CODE REVIEW

**Comment by fiery-phoenix** [comment]
Implementation is a little bit different from what was originally proposed at #751. flatMap and map don't throw AssertionError if actual optional is empty. From my point of view it would be more expected behavior. As map() doesn't extract mapped value, have added extractingValue() method as it was proposed at #748.

**Comment by joel-costigliola** [comment]
Sweet, will review it this we.

**Comment by joel-costigliola** [comment]
Thanks @fiery-phoenix ! 
I have modified a bit your PR, I have left out `extractingValue()` as I'm not sure it is totally useful (waiting for feedback on that) and I have added support for soft assertions (a tricky part of AssertJ code).

**Comment by fiery-phoenix** [comment]
Ok, thank you!

**Pull request closed without merging**
