### PR TITLE
Fixes #1441 use raw string when given no arguments

### LINKED ISSUE #1441: UnknownFormatConversionException when asserting String with `%` sign
#### Summary
I have a test written in Kotlin. It throws `UnknownFormatConversionException` when I try to assert a String containing `%` character. The same test in Java works properly. 

  > A hint: Java test calls method `org.assertj.core.api.AbstractAssert#isEqualTo`, while Kotlin test calls `org.assertj.core.api.AbstractStringAssert#isEqualTo` (which is buggie when there is no args). 

#### Example

1. Test in Java - works:

```java
import org.junit.Test;
import static org.assertj.core.api.Assertions.assertThat;

public class AssertJTest {
  @Test
  public void assertJ12() {
    assertThat("foo %").isEqualTo("foo %");
  }
}
```

2. The same test in Kotlin - fails:

```kotlin
import org.assertj.core.api.Assertions.assertThat
import org.junit.Test

class AssertJTest {
  @Test
  fun assertJ12() {
    assertThat("foo %").isEqualTo("foo %")
  }
}
```

Failure message is:

```java
java.util.UnknownFormatConversionException: Conversion = '%'
	at java.base/java.util.Formatter.checkText(Formatter.java:2732)
	at java.base/java.util.Formatter.parse(Formatter.java:2718)
	at java.base/java.util.Formatter.format(Formatter.java:2655)
	at java.base/java.util.Formatter.format(Formatter.java:2609)
	at java.base/java.lang.String.format(String.java:2897)
	at org.assertj.core.api.AbstractStringAssert.isEqualTo(AbstractStringAssert.java:310)
	at controllers.api.AssertJTest.assertJ12(AssertJTest.kt:9)
```

### PR DESCRIPTION
**Pull request by asolntsev**
#### Check List:
* Fixes #1441 
* Unit tests : NO 
* Javadoc with a code example (API only) : NA

### CODE REVIEW

**Comment by joel-costigliola** [comment]
Thanks @asolntsev, can you add a test for the overridden `isEqualTo` that checks it delegates to its parent method, it should be possible to do so with mockito with callRealMethod or spy

**Comment by asolntsev** [comment]
@joel-costigliola As I know, it's not possible to verify that super.something() was called. 
And even if it was possible, would be such test really useful? 

A much better alternative is to add a test in Kotlin which would actually fail with current AssertJ implementation. But do you want to introduce kotlin to AssertJ project?..

**Comment by joel-costigliola** [comment]
just want to make sure that the method is called in tests (which probably is but let's verify that).

Although I like Kotlin, I don't want to have a dependency on it.

**Comment by joel-costigliola** [comment]
Integrated thanks @asolntsev!

**Pull request closed without merging**
