### PR TITLE
Set Java module version to project's version

### PR DESCRIPTION
**Pull request by sormuras**
`jar --describe-module --file assertj-core-3.13.0-SNAPSHOT.jar --release 9`

yields:
```
releases: 9

org.assertj.core@3.13.0-SNAPSHOT jar:file:///R:/dev/github/sormuras/assertj-core/target/assertj-core-3.13.0-SNAPSHOT.jar/!META-INF/versions/9/module-info.class

exports org.assertj.core.annotations
exports org.assertj.core.api
exports org.assertj.core.api.exception
exports org.assertj.core.api.filter
exports org.assertj.core.api.iterable
exports org.assertj.core.api.recursive.comparison
exports org.assertj.core.condition
exports org.assertj.core.configuration
exports org.assertj.core.data
exports org.assertj.core.description
exports org.assertj.core.error
exports org.assertj.core.error.future
exports org.assertj.core.error.uri
exports org.assertj.core.extractor
exports org.assertj.core.groups
exports org.assertj.core.internal
exports org.assertj.core.matcher
exports org.assertj.core.presentation
exports org.assertj.core.util
exports org.assertj.core.util.diff
exports org.assertj.core.util.diff.myers
exports org.assertj.core.util.introspection
exports org.assertj.core.util.xml

requires java.base mandated
requires java.instrument
```

### CODE REVIEW

**Comment by joel-costigliola** [comment]
I guess I can close this one since I already pushed a module-info in master

**Comment by sormuras** [comment]
This PR added the `@3.13.0-SNAPSHOT` in `org.assertj.core@3.13.0-SNAPSHOT` via a `javac` option `--module-version` configured in AssertJ's `pom.xml`.

Compiling the version into a module (descriptor) allows user's stacktraces to contain that information as well. No need to ask for the version of AssertJ used if you receive a stacktrace ... from the module-path.

**Comment by joel-costigliola** [comment]
Fair enough!

**Comment by sormuras** [comment]
Want me to rebase it? Or do you want to just add those two lines on `master`.

```
<arg>--module-version</arg>
<arg>${project.version}</arg>
```

**Comment by joel-costigliola** [comment]
Integrated thanks !

**Pull request closed without merging**
