### PR TITLE
use Preconditions#checkNotNull instead of throwing a NullPointerException

### PR DESCRIPTION
**Pull request by PascalSchumacher**
If you prefer the usage without a static import I will update the pull request accordingly.

### CODE REVIEW

**Comment by joel-costigliola** [comment]
No it's ok, static import are fine when they make the code more readable.

**Comment by PascalSchumacher** [comment]
Just noticed that this will not work on older android versions: http://stackoverflow.com/questions/28613784/noclassdeffounderror-java-util-objects-android

So merging this would break the support of android versions supporting only java 6 added with https://github.com/joel-costigliola/assertj-core/pull/521

**Comment by joel-costigliola** [comment]
Let's not use it then, I'm gonna remove the two places where `java.util.Objects` is used.

**Comment by joel-costigliola** [comment]
I actually like the idea, let's introduce our `requireNonNull` in `org.assertj.core.util.Objects`.

**Comment by PascalSchumacher** [comment]
O.k. I will update the pull request.

**Comment by PascalSchumacher** [comment]
I changed the pull request to use `Preconditions#checkNotNull` instead of `Objects#requireNonNull`.

**Comment by joel-costigliola** [comment]
:+1:

**Comment by joel-costigliola** [comment]
Integrated, thanks.

**Pull request closed without merging**
