### PR TITLE
Android support for v2.x

### PR DESCRIPTION
**Pull request by Turbo87**
This PR continues #500. Please doublecheck if this change has any undesired side effects.

### CODE REVIEW

**Comment by joel-costigliola** [comment]
Sadly, some projects (including mine at work) have rules to prevent using inherited static methods, that would prevent using the inherited `Java6Assertions`. The only option is duplicating the class and removing `Path` assertions which makes me sad but I don't see any other options.

I'll make the change if you are busy ...

**Comment by Turbo87** [comment]
that is exactly the side effect I was afraid of. IntelliJ didn't complain about that sort of thing by default but I can see how that would be a no-go for some people... I'm wondering if there is a way to automatically generate such a class instead of all the code duplication

**Comment by joel-costigliola** [comment]
Well, generating the `Assertions` class would require two things:
* introspect everything the implements `Assert` 
* annotate all the utility methods exposed (like `offset`) 
but I'm not sure if we can deal easily with generic method like `offset`, how do you know you have to generate versions for `Double` and `Float` ?

It is simpler to duplicate stuff, if we miss something, users will complain and we will fix it in the next version - not ideal but pragmatic.

**Comment by joel-costigliola** [comment]
Integrated, thanks @Turbo87

**Comment by kxfang** [comment]
Hi, does the work done here cover SoftAssertions? With Android projects I'm seeing the same old nio Path issue when SoftAssertions are used.

**Comment by joel-costigliola** [comment]
No :( but contributions are welcomed ;-)

**Comment by kxfang** [comment]
Guess I'll do something similar to the Java6Assertions patch.

**Pull request closed without merging**
