### PR TITLE
#356 Assertions for URI and URL

### PR DESCRIPTION
**Pull request by AlexBischof**
Created structures and packages for the issue containing also the assertions hasScheme and hasPathEquals (test classes included). But one problems remains with the core api tests because java.net.URL cannot be mocked because of final class. I guess that powermock or JMockit is not an option so how should i proceed?

### CODE REVIEW

**Comment by joel-costigliola** [comment]
Thanks Alex.
We should stick to the JDK API and use `hasPath` instead of `hasPathEquals`

**Comment by AlexBischof** [comment]
In the issue the name was hasPathEquals ;)

**Comment by joel-costigliola** [comment]
Yep, this is something that I commented in #356

**Comment by joel-costigliola** [comment]
Fixed after much additional work to support URL.

**Pull request closed without merging**
