### PR TITLE
Junit 5

### PR DESCRIPTION
**Pull request by PascalSchumacher**

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
Everything other than `AbstractTemporalAssert_isCloseTo_Test` and the SoftAssertionsRule tests converted to use JUnit 5.

Not sure why the travis on java 10 failed with:

```[[1;34mINFO[m] [1m--- [0;32mmaven-bundle-plugin:3.5.0:bundle[m [1m(default-bundle)[m @ [36massertj-core[0;1m ---[m
[[1;33mWARNING[m] Error injecting: org.apache.felix.bundleplugin.BundlePlugin
[1;31mjava.lang.NoClassDefFoundError[m: [1;31maQute/bnd/osgi/Analyzer[m
```

This seems unrelated.

**Comment by joel-costigliola** [comment]
seems to be a maven bnd plugin error, similar issue but different version: https://forum.predix.io/questions/23172/maven-install-error-in-sample-subscriptionmachinea.html

**Comment by joel-costigliola** [comment]
I created this: https://issues.apache.org/jira/browse/FELIX-5890

**Comment by PascalSchumacher** [comment]
Thanks. Downgrading the `maven-bundle-plugin` to version `3.4.0` fixes the build.

**Comment by joel-costigliola** [comment]
Thanks @PascalSchumacher !

**Pull request merged**
