### PR TITLE
fixes #641 to add a NavigationListAssert for being able to navigate into elements in a list and chain assertions

### LINKED ISSUE #641: add a NavigationListAssert<T,EA> extends ListAssert<T> for easier navigation through generated Assert models
this is an implementation class used to provide generated navigation methods through generated Assert classes. 

For background see this whole thread for https://github.com/joel-costigliola/assertj-assertions-generator/issues/67

In particular for [here's an example navigating through lists](https://github.com/joel-costigliola/assertj-assertions-generator/issues/67#issuecomment-208756239)

So these classes are really intended to be reused by folks generating assertion classes using navigable list properties.

PR on its way shortly...

### PR DESCRIPTION
**Pull request by jstrachan**
fixes #641 to add a NavigationListAssert for being able to navigate into elements in a list and chain assertions

### CODE REVIEW

**Comment by joel-costigliola** [comment]
@jstrachan I'm not fond of the `Descriptions` class, I'd like to meld it into `NavigationListAssert`, can you give me a reason not to ?

**Comment by jstrachan** [comment]
TBH I'm not solid on the Descriptions class either ;). Given its only one simple method I'm totally happy with your approach of using NavigationListAssert

**Comment by joel-costigliola** [comment]
cool :)
I have made good progress on #641 based on your work, I'm not finished though, I'm gonna try allowing navigation on `Iterable` instead of being limited to `List`.

**Comment by jstrachan** [comment]
Great stuff thanks! Yeah working on Iterable/Collection/Set would be handy too.

**Comment by joel-costigliola** [comment]
Done ... finally, thanks @jstrachan I have modified few things from the original PR, don't hesitate to have a look and tell me if I screwed up !

**Pull request closed without merging**
