### PR TITLE
Allow to register custom object formatter in error messages #455

### PR DESCRIPTION
**Pull request by PascalSchumacher**
I would like to use this feature, so I put together a quick prototype. If you rather not expose `Representation`, I'm open to every other approach.

### CODE REVIEW

**Comment by joel-costigliola** [comment]
Cool, will look into it soon but first I'm preparing 2.4.0/3.4.0 releases

**Comment by PascalSchumacher** [comment]
No need to hurry.

Nice to hear that 2.4.0/3.4.0 will be released soon. :smiley:

**Comment by joel-costigliola** [comment]
I think this is on the right track, I'm going to continue it, I want to refactor the `Representation` hierarchy and introduce a few things:
* a way to register a representation globally (not having to specify it for each assertions)
* a way to register in the current representation the description of a specific type without having to create a new representation (I think it is only possible using Java 8 lambda though)

**Comment by PascalSchumacher** [comment]
Great, these enhancements will make the feature much more powerful. :+1:

**Comment by PascalSchumacher** [comment]
Was merged and greatly improved upon by @joel-costigliola ! Thanks!

See https://github.com/joel-costigliola/assertj-core/issues/455 for details.

**Pull request closed without merging**
