### PR TITLE
Fixes #386 : Replace JUnit assertions with AssertJ in AssertJ tests

### LINKED ISSUE #372: Feature request: doesNotStartWith and doesNotEndWith assertions on CharSequence
Provide complementary assertions to:
* https://github.com/joel-costigliola/assertj-core/blob/master/src/main/java/org/assertj/core/api/AbstractCharSequenceAssert.java#L471
* https://github.com/joel-costigliola/assertj-core/blob/master/src/main/java/org/assertj/core/api/AbstractCharSequenceAssert.java#L445

### LINKED ISSUE #386: In AssertJ tests, replace JUnit assertions by AssertJ
When possible, we should avoid to use JUnit assertions in assertj tests.
Using this script should be a good way of achieving this : https://github.com/joel-costigliola/assertj-core/blob/master/src/main/scripts/convert-junit-assertions-to-assertj.sh .

### PR DESCRIPTION
**Pull request by mkordas**

### CODE REVIEW

**Comment by joel-costigliola** [comment]
fix for #386 ?

**Comment by mkordas** [comment]
Thats right, commit message should be 'Fixes #386 : Replace JUnit assertions with AssertJ in AssertJ tests'. Can you reword it while integrating?

**Comment by joel-costigliola** [comment]
:+1:

**Comment by joel-costigliola** [comment]
Have you used your script ? 
In that case can you rerun it, I don't want to spend too much time resolving merge conflicts it we can just run the script again.

**Comment by mkordas** [comment]
Yes, I've used the script, but it required huge number of manual corrections afterwards. The script do not support multiline assertions and assertions for strings that contains commas. And we have dozens of such assertions for error messages in AssertJ.

Do you want me to rebase and resolve merge conflicts?

**Comment by joel-costigliola** [comment]
That would be awesome, thanks !
If you don't feel for it or don't have time, I'll do it.

**Comment by mkordas** [comment]
@joel-costigliola - rebase done, commit reworded

**Comment by joel-costigliola** [comment]
Integrated, thanks A LOT !

**Pull request closed without merging**
