### PR TITLE
Fixes #672: adds Java6SoftAssetions to allow use with Android projects

### LINKED ISSUE #672: SoftAssertions do not work in Android projects due to nio.Path dependency

### PR DESCRIPTION
**Pull request by kxfang**
Extracted Java 6 compatible AbstractStandardSoftAssertions to a Java6AbstractStandardSoftAssertions super class and duplicated SoftAssertions.

### CODE REVIEW

**Comment by joel-costigliola** [comment]
thanks @kxfang  !

**Comment by kxfang** [comment]
Happy to help. Any estimates for when the next release might be?

**Comment by joel-costigliola** [comment]
By the end of the month.

One thing came to mind after merging the PR : adding `Java6JUnitSoftAssertions`, I think they could be useful as one does not need to to call `assertAll()` as long as they declared `Java6JUnitSoftAssertions` as a JUnit Rule.

**Comment by kxfang** [comment]
Ahh yeah, good idea. I wasn't aware that there's already a JUnit rule. Feel free to open an issue and assign to me.

**Pull request merged**
