### PR TITLE
Retain assertion state in asInstanceOf()

### LINKED ISSUE #1517: asInstanceOf() should retain description
Currently `asInstanceOf()` is not keeping the existing assertion description.

To achieve it, the return statement of:

https://github.com/joel-costigliola/assertj-core/blob/aee33e05bdba3e39376abd9083941c5fc632a905/src/main/java/org/assertj/core/api/AbstractAssert.java#L371-L373

should be changed to:

```java
return instanceOfAssertFactory.createAssert(actual).as(info.description());
```

but this cannot work with the current method declaration because of the type parameter `ASSERT` extending `Assert<?, ?>` instead of `Assert<ASSERT, ?>`.

To fix it, some changes would be needed which cause the replacement of all the `assertThat()` abstract return types with the corresponding concrete ones.

My main question is: why are some `assertThat()` returning an abstract class instead of the concrete one, while others (e.g., `assertThat(Class<?>`) are already returning concrete types? 
Is there a design reason behind it which I'm not understanding?

### PR DESCRIPTION
**Pull request by scordio**
#### Check List:
* Fixes #1517
* Unit tests : YES
* Javadoc with a code example (API only) : NA

### CODE REVIEW

**Comment by scordio** [comment]
Hi @joel-costigliola, did you have a chance to take a look at this PR? I'd like to propose another PR related to `asInstanceOf()` but I prefer to consolidate this one first.

**Comment by joel-costigliola** [comment]
@scordio I was about to do it but I got stuck on the java modules issue, will have a look this we!

**Comment by scordio** [comment]
@joel-costigliola thanks, take your time!

**Comment by joel-costigliola** [comment]
Good work @scordio  (as usual !), this is integrated.

**Pull request closed without merging**
