### PR TITLE
Add assumptions it tests

### PR DESCRIPTION
**Pull request by scordio**
This covers the cases mentioned in #1961 and #1985. Any other relevant use case to cover?

### CODE REVIEW

**Comment by joel-costigliola** [comment]
I think that should be enough as JUnit 5 + opentest4j is done in the main project. 
Maybe add JUnit 4 + 5 for projects that migrate slowly to JUnit 5? not so sure it is 100% relevant

**Comment by scordio** [comment]
> Maybe add JUnit 4 + 5 for projects that migrate slowly to JUnit 5? not so sure it is 100% relevant though

At least it would protect against unintended changes, forcing it to be on purpose. I will add this case.

**Comment by scordio** [comment]
>  Maybe add JUnit 4 + 5 for projects that migrate slowly to JUnit 5? not so sure it is 100% relevant though

On second thought, JUnit 4 + 5 would lead to the same case as JUnit 4 + opentest4j.

Also, projects that are migrating slowly to JUnit 5 would probably use JUnit 5 together with the `junit-vintage-engine`, so they would probably avoid JUnit 4 in the classpath (and if they don't, they are falling back to the case above).

**Comment by joel-costigliola** [comment]
Alright, let's integrate that PR then

**Pull request merged**
