### PR TITLE
Instant assertion

### LINKED ISSUE #903: Add Instant assertion
#### Summary

The main of Java 8 java.time.* are supported except `Instant`

### PR DESCRIPTION
**Pull request by epeee**
#### Check List:
* Fixes #903 
* Unit tests : YES
* Javadoc with a code example (API only) : YES

a very first implementation, we might add some additional methods in another pr

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
Hi epeee,

thanks for the pull request! :smile:

It would be nice if you would add since javadoc tags.

Thanks,
Pascal

**Comment by epeee** [comment]
thx @PascalSchumacher. I completely forgot about it in classes other than `InstantAssert` and `AbstractInstantAssert`. Added the missing ones just a moment ago.

**Comment by PascalSchumacher** [comment]
Thanks!

**Comment by joel-costigliola** [comment]
@PascalSchumacher I'm away next week, would you mind reviewing and integrating this PR when everything looks fine ?

**Comment by PascalSchumacher** [comment]
@joel-costigliola I will probably have time to review this pull request this weekend.

**Comment by PascalSchumacher** [comment]
Merged. Thanks a lot! :+1: 

By the way: It is not necessary to add since javadoc tags to every method for new classes. It's sufficient to add this tag to the class. :)

**Pull request closed without merging**
