### PR TITLE
Fix for #514

### PR DESCRIPTION
**Pull request by DanCorder**
Changes to implement 'isNotEqualToIgnoringWhitespace' assertion.

### CODE REVIEW

**Comment by joel-costigliola** [comment]
Thanks, will have a look at it soon.

**Comment by DanCorder** [comment]
I'm not very happy about the way that JUnit handles parameterised tests. Would you be OK with adding something like https://github.com/Pragmatists/junitparams or https://github.com/piotrturski/zohhak as a test dependency to the project?

**Comment by joel-costigliola** [comment]
Yes  no problem, I kinda like https://github.com/piotrturski/zohhak better.

**Comment by PascalSchumacher** [comment]
https://github.com/TNG/junit-dataprovider is another possibility

**Comment by DanCorder** [comment]
Ok, I'll do a separate patch for parameterised tests, as they are used in other places too.

**Comment by joel-costigliola** [comment]
Thanks Dan, integrated.

**Pull request closed without merging**
