### PR TITLE
Add predicate descriptions to methods

### LINKED ISSUE #756: ObjectArrayAssert: Add allMatch(Predicate, String) with predicateDescription
#### Summary

It should be possible to provide a predicate description in [`ObjectArrayAssert#allMatch(Predicate)`](https://github.com/joel-costigliola/assertj-core/blob/fe84371353fa3f74ea574e04a9480c986f77e6fb/src/main/java/org/assertj/core/api/AbstractObjectArrayAssert.java#L2194-L2197).

So far, this is only possible when matching the object using [`AbstractAssert#matches(Predicate, String)`](https://github.com/joel-costigliola/assertj-core/blob/affd2994fb757fb9e35be1372e976f50942f7a86/src/main/java/org/assertj/core/api/AbstractAssert.java#L534-L536) rather than its elements.

#### Example

```java
// Note: MimeMessageToBodyAsStringExtractor extracts a String of the content
// of the first BodyPart of the Content of the MimeMessage (Workaround for #755).

MimeMessage[] messages = fetchReceivedMessages(); // Fetches messages from GreenMail.

assertThat(messages)
  .as("Received messages")
  .hasSize(2)

  .extracting(new MimeMessageToBodyAsStringExtractor())
  .as("Body of messages")
  .allMatch(body -> body.contains("Powered by AssertJ."), "Should contain acknowledgement.");
```

#### Java 8 specific ?

* NO  : create Pull Request from the `2.x` branch

### PR DESCRIPTION
**Pull request by filiphr**
* Fixes #756 
* Unit tests : YES 
* Javadoc with a code example (API only) : YES

### CODE REVIEW

**Comment by joel-costigliola** [comment]
Thanks, will review it in the next couple weeks.

**Comment by filiphr** [comment]
@joel-costigliola I missed your message for some reason. Which code do you think should go in the 2.x branch? I think that the entire code is Java 8 based. Everything that I changed is related to Java 8 assertions with `Predicate`

**Comment by joel-costigliola** [comment]
@filiphr you are right, forget my stupid comment (facepalm)

**Comment by joel-costigliola** [comment]
Merged, thanks Filip !

**Pull request closed without merging**
