### PR TITLE
No need to use FQN for imported names

### PR DESCRIPTION
**Pull request by pzygielo**

### CODE REVIEW

**Comment by joel-costigliola** [comment]
Integrated thanks @pzygielo!

**Comment by pzygielo** [comment]
Thanks for checking.
I see some leftovers however: https://github.com/joel-costigliola/assertj-core/compare/master...pzygielo:fqn
Are they missed or kept on purpose?
GIVEN is already imported and used without class qualification in other places in that file.
The same for Arrays.stream.

**Comment by joel-costigliola** [comment]
I left them as I felt the code was less clear with GIVEN only and for stream it would have changed the code formatting not to align the chained methods.

**Comment by pzygielo** [comment]
> I left them as I felt the code was less clear with GIVEN only

I see. But for example in the same file - https://github.com/joel-costigliola/assertj-core/blob/63caf5d81afcef58db11717a1eff14e80c797f60/src/main/java/org/assertj/core/api/AbstractPredicateAssert.java#L65 is clear enough, right?

**Comment by joel-costigliola** [comment]
good point, I'll change that for consistency

**Pull request closed without merging**
