### PR TITLE
introduce throwingextractor

### LINKED ISSUE #755: ObjectArrayAssert: Allow extracting single value using Function
#### Summary

It should be possible to extract a single value in an [`ObjectArrayAssert`](https://github.com/joel-costigliola/assertj-core/blob/fe84371353fa3f74ea574e04a9480c986f77e6fb/src/main/java/org/assertj/core/api/AbstractObjectArrayAssert.java#L1648-L1652) using a `Function`.

So far, there is only [`AbstractObjectArrayAssert#extracting(Function<T, ?>...)`](https://github.com/joel-costigliola/assertj-core/blob/fe84371353fa3f74ea574e04a9480c986f77e6fb/src/main/java/org/assertj/core/api/AbstractObjectArrayAssert.java#L1704-L1716) which returns a `ObjectArrayAssert<Tuple>`, even if only one `Function` is given.

There are two solutions for this:
1. Change signature of [`AbstractObjectArrayAssert#extracting(Extractor<? super T, U>)`](https://github.com/joel-costigliola/assertj-core/blob/fe84371353fa3f74ea574e04a9480c986f77e6fb/src/main/java/org/assertj/core/api/AbstractObjectArrayAssert.java#L1648-L1652) to `AbstractObjectArrayAssert#extracting(Function<T, U>)`.
2. Add `AbstractObjectArrayAssert#extracting(Function<T, U>)`.

_Note_: For this, the [`FieldOrPropertiesExtractor`](https://github.com/joel-costigliola/assertj-core/blob/ff021db1c1cbe02b24998228d5659f5eca00d0a6/src/main/java/org/assertj/core/groups/FieldsOrPropertiesExtractor.java#L36) probably needs to be extended to support `Function`s.
#### Example

``` java
// Note: unchecked(Function<T,R>) wraps a Function and effectively removes exceptions 
// from its signature by wrapping these exceptions in a RuntimeException.

MimeMessage[] messages = fetchReceivedMessages(); // Fetches messages from GreenMail.

assertThat(messages)
  .as("Received messages")
  .hasSize(2)

  .extracting(unchecked(message -> (MimeMultipart) message.getContent())
  .as("Content of message")
  .isNotNull()

  .extracting(unchecked(content -> content.getBodyPart(0))
  .as("First body part of message")
  .isNotNull()

  .extracting(unchecked(body -> (String) body.getContent()))
  .as("Body of messages")
  .isNotNull()
  .allMatch(body -> body.contains("Powered by AssertJ.")); // Description requires #756
```
#### Java 8 specific ?
- YES : create Pull Request from the `master` branch

### PR DESCRIPTION
**Pull request by epeee**
#### Check List:
* Fixes #755
* Unit tests : YES
* Javadoc with a code example (API only) : YES

### CODE REVIEW

**Comment by joel-costigliola** [comment]
@epeee if you have time, can you add `flatExtracting` variants  taking `ThrowingExtractor` to keep AssertJ API consistent ?

**Comment by epeee** [comment]
@joel-costigliola yes, I will add `flatExtracting` variants. Thx for pointing that out.

**Comment by PascalSchumacher** [comment]
@epeee It would be nice if you could rebase the pull request on current master. Thanks!

**Comment by epeee** [comment]
@PascalSchumacher the pr is rebased now.

**Comment by PascalSchumacher** [comment]
Thanks!

**Comment by joel-costigliola** [comment]
Integrated, thanks @epeee !

**Pull request closed without merging**
