### PR TITLE
Fix typo in error message factories (#1506)

### LINKED ISSUE #1506: Typo in AbstractDateAssert#isBeforeOrEqualsTo method name?
#### Summary
`AbstractDateAssert#isBeforeOrEqualsTo` has a trailing 's' in 'Equals' and it looks like a typo compared to java 8 time assertions (same for `AbstractDateAssert#isAfterOrEqualsTo`). It is just a style issue and fixing it would be a backwards incompatible change.

Also `org.assertj.core.error.ShouldBeBeforeOrEqualsTo` and `org.assertj.core.error.ShouldBeAfterOrEqualsTo` have the same flaw.

#### Example

```java
assertThat(new Date).isBeforeOrEqualsTo(anotherDate)
assertThat(Instant.now()).isBeforeOrEqualTo(anotherInstant)
```

### PR DESCRIPTION
**Pull request by scordio**
#### Check List:
* Fixes #1506
* Unit tests : NA
* Javadoc with a code example (API only) : NA

### CODE REVIEW

**Comment by joel-costigliola** [comment]
Good catches (again!), thanks a lot @scordio!

**Comment by scordio** [comment]
Done, I did a bit of test refactoring: the error message factories have already a unit test so I wouldn't verify again their string output in each test for other assertion classes.

**Comment by scordio** [comment]
I fixed some missing static imports after the renaming. I don't understand why git is swapping the files instead of catching the right renaming 🤔 but overall it looks fine!

**Comment by joel-costigliola** [comment]
Thanks for the refactoring, avoiding repeating the error message is much better (and is the preferred style of testing).

**Pull request merged**
