### PR TITLE
2.x biginteger

### LINKED ISSUE #811: Support for BigIntegers similar to BigDecimal?
Is there any reason `BigInteger`s don't have similar support to `BigDecimal`s? I just replaced all my `int`s in a project with `BigInteger`s (because of serialization/deserialization issues) and wrote some code to support `BigInteger` asserts that take `int`s, `long`s, and `String`s as the argument of `isEqualTo`. I'd be happy to donate my code back to the project, but want to make sure it's something people would want before I ask for permission to contribute at work.

### PR DESCRIPTION
**Pull request by epeee**
#### Check List:
* Fixes #811
* Unit tests : YES
* Javadoc with a code example (API only) : YES

### CODE REVIEW

**Comment by joel-costigliola** [comment]
Will review that this month (please comment on this issue if I don't)

**Comment by PascalSchumacher** [comment]
Merged by @joel-costigliola in https://github.com/joel-costigliola/assertj-core/commit/9b3016d8232d662e2e020552941125a425485a30

Thanks for the pull request @epeee! 👍

**Comment by joel-costigliola** [comment]
Thanks a lot @epeee !

**Comment by epeee** [comment]
You're welcome!

**Pull request closed without merging**
