### PR TITLE
AbstractOptionalAssert: Replace contains() with hasValue()

### LINKED ISSUE #459: OptionalAssert.contains() vs. OptionalIntAssert.hasValue()
There is an inconsistency in the naming of the content check methods of the `Optional` class and primitive `OptionalInt/Long/...` classes. Either both should be supported or we should decide on one and keep it consistent.

### PR DESCRIPTION
**Pull request by Turbo87**
Resolves #459

### CODE REVIEW

**Comment by joel-costigliola** [comment]
cool, will review it in the next weeks.

**Comment by joel-costigliola** [comment]
`contains` added.

**Comment by Turbo87** [comment]
FWIW I would appreciate it if you would tell me that I should adjust my own commit instead of discarding it and writing a new one yourself... makes me wonder why I worked on that in the first place...

**Comment by joel-costigliola** [comment]
Hey Tobias sorry for that !

I just rewrote your commit for two reasons:
* you haven't adjusted your commit after my comment https://github.com/joel-costigliola/assertj-core/issues/459#issuecomment-120570879 
* it as it was a really quick task to fix the issue - it would have taken much more time to ask you (again) to update your commit, review it and integrate it (please remember that I'm quite busy these days).

Anyway, I apologize, I should have communicated better my expectations.

**Comment by Turbo87** [comment]
Sorry, then it seems I misunderstood your comment. I've only created that commit *after* reading that comment and thought that you preferred `hasValue()` over `contains()`.

**Comment by joel-costigliola** [comment]
No problem, I thought indeed it was a misunderstanding ;-)

**Pull request closed without merging**
