### PR TITLE
Fixes: #1145 - `isEqualToComparingFieldByFieldRecursively` throws Nul…

### LINKED ISSUE #1145: `isEqualToComparingFieldByFieldRecursively` throws NullPointerException while comparing null values
#### Summary

If a nested field is null while comparing equality for two objects with `isEqualToComparingFieldByFieldRecursively` a NullPointerException is thrown.

### Stacktrace

```
Exception in thread "main" java.lang.NullPointerException
	at org.assertj.core.error.ShouldBeEqualByComparingFieldByFieldRecursively.describeDifference(ShouldBeEqualByComparingFieldByFieldRecursively.java:67)
	at org.assertj.core.error.ShouldBeEqualByComparingFieldByFieldRecursively.shouldBeEqualByComparingFieldByFieldRecursive(ShouldBeEqualByComparingFieldByFieldRecursively.java:32)
	at org.assertj.core.internal.Objects.assertIsEqualToComparingFieldByFieldRecursively(Objects.java:728)
	at org.assertj.core.api.AbstractObjectAssert.isEqualToComparingFieldByFieldRecursively(AbstractObjectAssert.java:653)
...
```

#### Example

```java
class Main {

    static class Value {
        private final String v;

        public Value(String v) {
            this.v = v;
        }
    }

    public static void main(String[] args) {
        Value actual = new Value(null); //swapping actual and expected leads to the same error
        Value expected = new Value("something");
        Assertions.assertThat(expected).isEqualToComparingFieldByFieldRecursively(actual);
    }

}
```

#### Java 8 specific ?

* YES
Tested with Version 3.9.0

### PR DESCRIPTION
**Pull request by siladu**
…lPointerException while comparing null values

#### Check List:
* Fixes #1145
* Unit tests : YES
* Javadoc with a code example (API only) : NA

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
@joel-costigliola I think we should also fix this in 2.x, what do you think?

**Comment by joel-costigliola** [comment]
yes it should but I can take of that, thanks for the PR  I'll review it shortly

**Comment by joel-costigliola** [comment]
fixed in master for 3.9.1

**Comment by Skylark95** [comment]
@joel-costigliola @PascalSchumacher Will a 2.x release be done for this. Issue is still present as of 2.9.0.

**Comment by joel-costigliola** [comment]
@Skylark95 will do in couple weeks

**Pull request closed without merging**
