### PR TITLE
#4 : Add missing javadoc code examples for DoubleAssert.

### PR DESCRIPTION
**Pull request by PascalSchumacher**

### CODE REVIEW

**Comment by joel-costigliola** [comment]
Thanks.
I don't think it adds a lot of value to use `Double.valueOf()` in the examples.
Can you update the example using `double` directly ?

Cheers

**Comment by PascalSchumacher** [comment]
I was not sure about the value of `Double.valueOf()` myself.

Pro: The examples actually test something (a bit more realistic).
Con: The examples are more complicated.

I guess it's good to make the examples as simple as possible. I will update the pull request.

Cheers, Pascal

**Comment by joel-costigliola** [comment]
Yeah, I agree that the examples related to `isEqualTo` and `isNotEqualTo` may seem "dumb" but it does not hurt.

**Comment by joel-costigliola** [comment]
Integrated, thx.

**Pull request merged**
