### PR TITLE
make hasBeenThrown public accessible

### PR DESCRIPTION
**Pull request by qoomon**
can be public without a doubt. I need this to have a test code like this:

   @Test
    public void expectExceptionLambda() throws Exception {
        // give
        Thrower thrower = new Thrower();

        // when
        Throwable exception = catchThrowable(() -> thrower.throwNullPointerException("boom"));

        // then
        assertThat(exception).hasBeenThrown().hasMessage("boom");
    }

### CODE REVIEW

**Comment by joel-costigliola** [comment]
You actually don't need to call `hasBeenThrown()` at all since `hasMessage` checks for `exception` not to be null.
The only difference would be the error message.

**Comment by qoomon** [comment]
Yes however i just need to check if there is an exception, the message does not matter.

**Comment by joel-costigliola** [comment]
you can use `isNotNull()` to check there is "something"

**Comment by qoomon** [comment]
maybe your right :-) but i will create an other PR for adding a better catchThrowable() Method to only catch explicit exceptions.

Thanks for response

**Comment by joel-costigliola** [comment]
Ok, looking forward to your PR.

**Pull request closed without merging**
