### PR TITLE
Make mockito to be a test-only dependency

### PR DESCRIPTION
**Pull request by testn**

### CODE REVIEW

**Comment by joel-costigliola** [comment]
Good catch ! :man_facepalming:

**Comment by PascalSchumacher** [comment]
It was already a test-only dependency, because version and scope were inherited from dependency management of the parent pom: https://github.com/joel-costigliola/assertj-maven-parent-pom/blob/master/pom.xml#L70

**Comment by joel-costigliola** [comment]
Reverted, thanks @PascalSchumacher for pointing this out. 

@testn to update the version, we need to change pom.xml in https://github.com/joel-costigliola/assertj-maven-parent-pom.

**Comment by testn** [comment]
oh thanks @PascalSchumacher  I didn't look there.

**Pull request merged**
