### PR TITLE
Added isCloseTo for temporal types

### LINKED ISSUE #796: add isCloseTo assertion for Java 8 java.time.* types
#### Summary

Add `isCloseTo` assertion for java 8 `java.time.*` types the [same way](https://github.com/joel-costigliola/assertj-core/blob/master/src/main/java/org/assertj/core/api/AbstractDateAssert.java#L2155) as for `java.util.Date`.

Preferably for all types of [java.time](http://docs.oracle.com/javase/8/docs/api/java/time/package-summary.html) package.

Most important types are:

- [ ] Instant
- [ ] LocalDate
- [ ] LocalDateTime
- [ ] LocalTime
- [ ] ZonedDateTime

#### Example

```java
Instant instant1 = Instant.now();
Instant instant2 = Instant.now();
assertThat(instant1).isCloseTo(instant2, 100); // 100 ms
```

Instead of:
```java
assertThat(instant1.toEpochMilli()).isCloseTo(instant2.toEpochMilli(), within(100L));
```
which also is not null-safe.

#### Java 8 specific ?

* YES : create Pull Request from the `master` branch

### PR DESCRIPTION
**Pull request by fiery-phoenix**
#### Check List:
* Fixes #796
* Unit tests : YES
* Javadoc with a code example (API only) : YES

Added isCloseTo only for existing asserters, if changes look more or less ok, will add InstantAssert as well.

### CODE REVIEW

**Comment by joel-costigliola** [comment]
Thanks, will review it by the end of the year.

**Comment by fiery-phoenix** [comment]
Ok

**Comment by PascalSchumacher** [comment]
I would be nice if you could add `@since 3.7.0` to the javadoc. Thanks!

**Comment by fiery-phoenix** [comment]
Done.

**Comment by joel-costigliola** [comment]
I finally got time to review and integrate this PR, thanks @fiery-phoenix.

You might be interested to know that I had to use `? super ` to get rid of some generic warnings when using the assertions described in the javadoc:
```java
// warning on within
assertThat(_07_10).isCloseTo(_07_42, within(32, ChronoUnit.MINUTES));
```
This was fixed by using `TemporalOffset<? super TEMPORAL> offset`  instead of `TemporalOffset<TEMPORAL> offset` in `isCloseTo`.

I have found that by testing the javadoc examples in assertj-examples which uses assertj like any project would do (an healthy way of being in user's shoes).

Thanks for the good work again, love the design and the javadoc.

**Comment by fiery-phoenix** [comment]
You are welcome. Thank you for the fix with usage of `? super` and other improvements.

**Pull request closed without merging**
