### PR TITLE
[Path|File|InputStream]Assert#hasDigest

### LINKED ISSUE #1210: Add PathAssert#hasDigest(MessageDigest, byte[])
#### Summary
I think this methods can be very useful for `PathAssert`, `FileAssert` and `InputStreamAssert`:
* `hasDigest(MessageDigest digest, byte[] expected)`
* `hasDigest(MessageDigest digest, String expected)`
* `hasDigest(String algorithm, byte[] expected)`
* `hasDigest(String algorithm, String expected)`
* `hasDigest(String algorithm, String provider, byte[] expected)`
* `hasDigest(String algorithm, String provider, String expected)`

#### Example

```java
URL source = new URL("https://search.maven.org/remotecontent?filepath=org/assertj/assertj-core/2.9.0/assertj-core-2.9.0.jar");
assertThat(source.openStream()).hasDigest("SHA1", "5c5ae45b58f12023817abe492447cdc7912c1a2c");
```

P.S.
I can create PR if you approve such methods.

### PR DESCRIPTION
**Pull request by valery1707**
Implement `[Path|File|InputStream]Assert#hasDigest` with 4 variants:
* `hasDigest(MessageDigest digest, byte[] expected)`
* `hasDigest(MessageDigest digest, String expected)`
* `hasDigest(String algorithm, byte[] expected)`
* `hasDigest(String algorithm, String expected)`

Progress:
- [x] Core utils
- [x] PathAssert
- [x] FileAssert
- [x] InputStreamAssert
- [x] Javadoc with a code example (API only)

Fixes #1210

### CODE REVIEW

**Comment by valery1707** [comment]
This is only first part of work: I want to receive early feedback for assertions in `PathAssert` before implement assertions in `FileAssert` and `InputStreamAssert`.

**Comment by valery1707** [comment]
As I say in https://github.com/joel-costigliola/assertj-core/issues/1210#issuecomment-376845125 this PR was created from `master` branch, but I also have branch created from `2.x` branch and I can make PR for branch `2.x` too.

**Comment by PascalSchumacher** [comment]
The `2.x` branch is now in bugfix only mode (see: https://joel-costigliola.github.io/assertj/assertj-core-news.html#assertj-core-2.9.0), so there is need for a `2.x` pull request.

**Comment by valery1707** [comment]
Work completed, @joel-costigliola @PascalSchumacher please review.

Sorry for long delay.

**Comment by joel-costigliola** [comment]
looking at it, thanks @valery1707!

**Comment by joel-costigliola** [comment]
Integrated thanks @valery1707 !

**Pull request closed without merging**
