### PR TITLE
Added support for specifying a precision with which to compare elements of float arrays (fixes #505)

### LINKED ISSUE #505: Add offset support to float/double arrays check methods
Please add offset support to float/double arrays check, like you did with one double value check, without this I can't contains check double arrays, I get errors like this:
java.lang.AssertionError: 
Expecting:
  <[7.199999999999999,
    3.5999999999999996,
    -12.0,
    30.599999999999998,
    0.30000000000000004]>
to contain exactly (and in same order):
  <[7.2, 3.6, -12.0, 30.6, 0.3]>

### PR DESCRIPTION
**Pull request by PascalSchumacher**

### CODE REVIEW

**Comment by joel-costigliola** [comment]
Good work ! Integrated.

**Comment by PascalSchumacher** [comment]
Thanks!

It was just copy&paste of your work on doubles.

**Comment by joel-costigliola** [comment]
You got me, I was really praising myself ! :smile:

**Comment by PascalSchumacher** [comment]
:smile:

**Pull request closed without merging**
