### PR TITLE
 make tests that expect an exception to be thrown fail if no exception was thrown

### PR DESCRIPTION
**Pull request by PascalSchumacher**
…xpected exception was not thrown

### CODE REVIEW

**Comment by joel-costigliola** [comment]
thanks Pascal

**Comment by PascalSchumacher** [comment]
Thanks for merging all my non essential pull requests. :=)

**Comment by joel-costigliola** [comment]
Thanks again for your work, much appreciated.
Could you delete the branches in your repo that have been merged/squashed in assertj one ? 
that would make it easier for me to find the new branches you are working on, here's your branch list :D

```
 git remote show PascalSchumacher 
* remote PascalSchumacher
  Fetch URL: https://github.com/PascalSchumacher/assertj-core.git
  Push  URL: https://github.com/PascalSchumacher/assertj-core.git
  HEAD branch: master
  Remote branches:
    #247                                                                  tracked
    #667                                                                  tracked
    #779                                                                  tracked
    1.7.1                                                                 tracked
    676_custom_comparators                                                tracked
    AbstractThrowableAssert_Javadoc_improvements                          tracked
    RecursivelyElementComparator                                          tracked
    add_Comparable_isBetween_and_isStrictlyBetween                        tracked
    add_Comparable_isBetween_and_isStrictlyBetween_add_missing_since_tags tracked
    add_ThrowableAssert_hasNoSuppressedExceptions                         tracked
    add_future_assertions                                                 tracked
    add_missing_generic_parameters_to_map_entry_javadoc                   tracked
    add_missing_since_tags                                                tracked
    add_missing_since_tags_2                                              tracked
    add_missing_since_tags_3                                              tracked
    containsExactlyInAnyOrder_for_primitive_arrays                        tracked
    contributing_improvements                                             tracked
    deepDifference_increase_customComparator_priority                     tracked
    delete_redundant_tests                                                tracked
    delete_unused_test_class                                              tracked
    entry_point_javadoc                                                   tracked
    error_representation                                                  tracked
    fix_312_test                                                          tracked
    fix_BigDecimals_assertIsZero_Test                                     tracked
    fix_bddassertiontest_case                                             tracked
    fix_bddautocloseablesoftassertion_javadoc                             tracked
    fix_callingthrowable_examples_head                                    tracked
    fix_readme_typo                                                       tracked
    fix_some_todos                                                        tracked
    fix_test_name                                                         tracked
    fix_typo                                                              tracked
    gh-pages                                                              tracked
    hamcrest_condition                                                    tracked
    ignoreWhitespace_fix                                                  tracked
    improve_add_since_tags                                                tracked
    improve_contributing                                                  tracked
    int_methods_for_byte_arrays                                           tracked
    is_blank                                                              tracked
    java-8                                                                tracked
    java6_entry_point_class_comment                                       tracked
    javadoc_improvements                                                  tracked
    javadoc_javadoc                                                       tracked
    list_size_assertions                                                  tracked
    master                                                                tracked
    minimal_javadoc_improvements                                          tracked
    minimal_javadoc_improvements_2                                        tracked
    minimal_test_cleanup                                                  tracked
    more_close_to_tests                                                   tracked
    more_expected_exception                                               tracked
    path-assert                                                           tracked
    readme_updates                                                        tracked
    recursive                                                             tracked
    recursive_comparision                                                 tracked
    remove-cglib                                                          tracked
    remove_commented_out_code                                             tracked
    remove_easymock                                                       tracked
    remove_unnecessary_throws_declarations                                tracked
    scripts                                                               tracked
    simplify_is_empty_assertions                                          tracked
    simplify_some_assertions                                              tracked
    since                                                                 tracked
    single_collection_assertion                                           tracked
    small_improvements                                                    tracked
    small_javadoc_corrections                                             tracked
    small_javadoc_improvements_and_corrections                            tracked
    softassertions_line_numbers_master                                    tracked
    softassertions_linenumbers                                            tracked
    update_dependency_versions                                            tracked
    update_dependency_versions_2x                                         tracked
    update_dependency_versions_master                                     tracked
    update_junitdataprovider_version                                      tracked
    update_to_mockito_2                                                   tracked
    xml                                                                   tracked
```

**Comment by PascalSchumacher** [comment]
Sure will do. I have not delete them for a long time, sorry!

**Comment by PascalSchumacher** [comment]
done

**Pull request merged**
