### PR TITLE
#111: support for xml and xpath assertions

### PR DESCRIPTION
**Pull request by mpi**
This Pull Request contains following new assertions and methods:
```java
    CharSequence.asXml(),
    XmlNodeSetAssert.extractingXPath(String),
    XmlNodeSetAssert.isEmpty(),
    XmlNodeSetAssert.hasSize(int),
    XmlNodeSetAssert.contains(String...),
    XmlNodeSetAssert.containsOnly(String...),
    XmlNodeSetAssert.containsExactly(String...),
    XmlNodeAssert.isElement(),
    XmlNodeAssert.isAttribute(),
    XmlNodeAssert.isComment(),
    XmlNodeAssert.isTextNode(),
    XmlNodeAssert.isEqualTo(String).
```
Although there is still a hundred of new xml assertions that can be added to this list, I believe this PR is a good starting point.

@joel-costigliola:
While reviewing please look into the following more carefully:
* Instead of implementing ```findingNodeByXPath(String xpath)``` suggested in #111, I have introduced ```extractingXPath(String xpath)``` that return ```XmlNodeSetAssert```. It works in a similar way to ```IterableAssert``` and ```extracting```.  I haven't introduced ```findingNodeByXPath(String xpath)``` in the first place, because I believe that extracting multiple elements is a more commonly used scenario. A method ```findingNodeByXPath(String xpath)``` can be introduced later by delegating to ```extractingXPath(String xpath)``` and asserting that the size is equal to 1.
* I have introduced simple DSL for defining expected xml node, eg. attribute node can be created by ```"@attribute='value'"```. For more details please have a look on javadoc of ```XmlNodeSetAssert.isEqualTo(String)```,
* I have introduced an interface ```XmlNodeAssert``` with the following implementations: ```XmlElementAssert```, ```XmlAttributeAssert```, ```XmlTextNodeAssert```, ... . My intention was to create seeds for further more fine-grained assertions on individual node types.

What can be done next:
* ```asXml()``` to ```InputStreamAssert``` and ```FileAssert```,
* methods for finding single xml node: ```findingNodeByXPath(String xpath)```,
* methods for finding single xml node of particular type, eg. ```findingElementByXPath(String xpath)```, ```findingAttributeByXPath(String xpath)```, ...
* assertions valid only for particular types of nodes, eg. ```XmlAttributeAssert.hasValue(String)```, ```XmlElementAssert.hasChildren()```, ...

### CODE REVIEW

**Comment by YemiAjayiMSM** [comment]
@joel-costigliola, just wondering if there is any plan in the pipeline for getting this PR merged-in. I currently have some use-cases where the XML / XPath assertions functionality would be helpful.

**Comment by joel-costigliola** [comment]
@YemiAjayiMSM there is a lot of work to do before this can be merged, I must admit it has been pretty low in my priorities lately but I have more time now. I will try to get this done by the end of the year.

**Comment by mkordas** [comment]
@joel-costigliola, many people wait for this and we even created our own extension for AssertJ XML assertions (project heavily uses XML). I can share our experiences if you want.

**Comment by PascalSchumacher** [comment]
@YemiAjayiMSM You could give https://github.com/j-maly/SchematronAssert a try in the meantime.

**Comment by joel-costigliola** [comment]
@mkordas I would be interested indeed. Is it open source ?

**Comment by mkordas** [comment]
@joel-costigliola, we use it internally in the company, but I can share our experiences and ideas. Generally our API is really similar to the one from this PR, but we've added also namespace support plus `hasXPath` and `doesNotHaveXPath` assertions.

**Comment by joel-costigliola** [comment]
I'm not sure this one is gonna be addressed, comparing XML is a project on its own like http://www.xmlunit.org/ which is working on a 2.0 version that looks really promising.

I'm closing this issue but I might reconsider if a contributor wants to spend time on it.

**Pull request closed without merging**
