### PR TITLE
CompletableFuture Assertions

### LINKED ISSUE #461: CompletableFuture Assertions
Here is my work-in-progress proposal for [CompletableFuture](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html) assertions. Feedback is very welcome.

----

# CompletableFuture Assertions

A `CompletableFuture` describes an asynchronous operation result that will eventually be fulfilled.

## Methods

- `isDone()` - the future has a result (exception or regular result)
- `isCompletedExceptionally()` - the future as an exceptional result
- `isCancelled()` - the future was cancelled and due to that has a `CancellationException` result
- `get()` waits for and returns the result, throws a `CancellationException` or throws the exceptional result wrapped in an `ExecutionException`

## States

The `CompletableFuture` class can be in four different states:

- not completed / "incomplete" (`!isDone()`)
- completed normally / "completed" (`isDone() && !isCompletedExceptionally()`)
- completed exceptionally  / "failed" (`isCompletedExceptionally()`)
- cancelled (`isCancelled()`)

Pseudo code to extract the state as an enum value:

```java
if (!isDone())
    return NOT_COMPLETED;
    
if (!isCompletedExceptionally())
    return COMPLETED;
    
if (!isCancelled())
    return FAILED;
    
return CANCELLED;
```

### isDone()

```java
assertThat(future).isDone();

// -> Expecting incomplete future to be done
```

### isNotDone()

```java
assertThat(future).isNotDone();

// -> Expecting future with result:
//        <40>
//    not to be done

// -> Expecting future with exception:
//        <java.lang.RuntimeException: some random error>
//    not to be done

// -> Expecting cancelled future not to be done
```

### isCompletedExceptionally()

```java
assertThat(future).isCompletedExceptionally();

// -> Expecting incomplete future to have completed exceptionally

// -> Expecting future with result:
//        <40>
//    to have completed exceptionally
```

### isNotCompletedExceptionally()

```java
assertThat(future).isNotCompletedExceptionally();

// -> Expecting future with exception:
//        <java.lang.RuntimeException: some random error>
//    to not have completed exceptionally

// -> Expecting cancelled future to not have completed exceptionally
```

### isCancelled()

```java
assertThat(future).isCancelled();

// -> Expecting incomplete future to be cancelled

// -> Expecting future with result:
//        <40>
//    to be cancelled

// -> Expecting future with exception:
//        <java.lang.RuntimeException: some random error>
//    to be cancelled
```

### isNotCancelled()

```java
assertThat(future).isNotCancelled();

// -> Expecting cancelled future not to be cancelled
```

----

The following assertions do no map directly to `CompletableFuture` methods.

### isCompleted()

```java
assertThat(future).isCompleted();

// -> Expecting incomplete future to be completed

// -> Expecting future with exception:
//        <java.lang.RuntimeException: some random error>
//    to be completed

// -> Expecting cancelled future to be completed
```

### isNotCompleted()

```java
assertThat(future).isNotCompleted();

// -> Expecting future with result:
//        <40>
//    to not be completed
```

### isCompletedWith(T expected)

```java
assertThat(future).isCompletedWith("result");

// -> Expecting incomplete future to be completed

// -> Expecting future with exception:
//        <java.lang.RuntimeException: some random error>
//    to be completed

// -> Expecting cancelled future to be completed

// -> org.junit.ComparisonFailure: 
//     Expected :"result"
//     Actual   :"different result"
```

### isCompletedMatching(Predicate<? super T> predicate)

```java
assertThat(future).isCompletedMatching(result -> result < 40);

// -> Expecting incomplete future to be completed

// -> Expecting future with exception:
//        <java.lang.RuntimeException: some random error>
//    to be completed

// -> Expecting cancelled future to be completed

// -> Expecting:
//       <50>
//     to match given predicate.
```

### hasFailed()

```java
assertThat(future).hasFailed();

// -> Expecting incomplete future to have failed

// -> Expecting future with result:
//        <40>
//    to have failed

// -> Expecting cancelled future to have failed
```

### hasNotFailed()

```java
assertThat(future).hasNotFailed();

// -> Expecting future with exception:
//        <java.lang.RuntimeException: some random error>
//    to not have failed
```

### hasFailedWithThrowableThat()

```java
assertThat(future).hasFailedWithThrowableThat()
    .isInstanceOf(IllegalArgumentException.class)
    .hasMessage("something");

// -> Expecting incomplete future to have failed

// -> Expecting future with result:
//        <40>
//    to have failed

// -> Expecting cancelled future to have failed

// -> Expecting:
//        <java.lang.RuntimeException: some random error>
//    to be an instance of:
//        <java.lang.IllegalArgumentException>
//    but was instance of:
//        <java.lang.RuntimeException>
```

### PR DESCRIPTION
**Pull request by Turbo87**
Resolves #461

### CODE REVIEW

**Comment by Turbo87** [comment]
@joel-costigliola have you had a chance to take a look at this?

**Comment by joel-costigliola** [comment]
Not yet, but I haven't forgotten about it.

**Comment by Turbo87** [comment]
@joel-costigliola any news?

**Comment by joel-costigliola** [comment]
will review it after I finish the release of the assertion generator, probably at the end of the month.

**Comment by Turbo87** [comment]
\*remind\*

**Comment by joel-costigliola** [comment]
will tackle it soon, don't worry

**Comment by joel-costigliola** [comment]
@Turbo87 I have reviewed the PR, I'm happy with it (I just made few cosmetic changes) except for `hasFailed` assertions that I find confusing, I think it would be better to remove them and use chained instead, something like : 
```java
assertThat(future).isCompletedExceptionally().isNotCancelled();
```
We would also replace `hasFailedWithThrowableThat()` with:
```java
assertThat(future).isCompletedExceptionallyWithThrowableThat().hasMessage("boom");
```


Do you have any strong argument in favor of keeping `hasFailed` and co ?

**Comment by Turbo87** [comment]
@joel-costigliola technically you are right that there is no strong need for `hasFailed`, but to be honest when I first used futures I found it confusing that "canceled" was a special case of "completed exceptionally". To me Java futures can have four states: incomplete, completed, failed, cancelled and that is how I modelled the assertions. It is basically a convenience or a semantic simplification.

don't you think that `isCompletedExceptionallyWithThrowableThat()` might be a bit too long?

**Comment by joel-costigliola** [comment]
yes it's long ... another option would be 
```java
assertThat(future).isCompletedExceptionally().withThrowableThat().hasMessage("boom");
```

the problem with `hasFailed` is that it took me too much time to figure out what was the difference with `isCompletedExceptionally`, it's clear for you because you have defined the semantics, I think it will be confusing for other people so let's not add it for the time being if some users ask for it I will reconsider.
I like to stick with JDK API when possible although I agree it lacks a `failed` state.

**Comment by Turbo87** [comment]
@joel-costigliola have you worked with futures before (aside from this PR)? I think for someone who has worked with them for a bit the JavaDoc for `hasFailed()` should be pretty clear actually.

**Comment by joel-costigliola** [comment]
I would prefer not to rely on javadoc if possible, I would rather for something like: `hasFailedButNotCancelled()` which is longer but explicit.

yes I have worked with future but not  `CompletableFuture`

**Comment by joel-costigliola** [comment]
I kind of changed my mind and think now that `hasFailed` is nice but I will add some javadoc to make it clear what is the difference with `isCompletedExceptionally()`

**Comment by Turbo87** [comment]
Cool, thanks for reconsidering!

**Comment by joel-costigliola** [comment]
integrated with minor changes in the API :
* `isCompletedWith` rename to `isCompletedWithValue`
* `isCompletedMatching` rename to  `isCompletedWithValueMatching`

thanks !

**Comment by Turbo87** [comment]
@joel-costigliola thanks. are you planning to do a new release in the near future including this feature?

**Comment by joel-costigliola** [comment]
yes

**Comment by ivankennethwang** [comment]
@joel-costigliola is this included in v3.4.0? I'm using `assertThat().` but couldn't find isCompletedWithValue.

In my build.sbt I have `"org.assertj" % "assertj-core" % "3.4.0",`

**Comment by joel-costigliola** [comment]
it is, extract from assertj examples : 
```java
    CompletableFuture<String> completedFuture = CompletableFuture.completedFuture("something");
    assertThat(completedFuture).isCompleted()
                               .isCompletedWithValue("something")
                               .isCompletedWithValueMatching(result -> result.startsWith("some"))
                               .isCompletedWithValueMatching(result -> result.startsWith("some"), "error message")
                               .isDone();
```
You shuld double check your classpath

**Pull request closed without merging**
