### PR TITLE
Extended iterables elements comparison by type to (#752)

### LINKED ISSUE #752: Allow to specify type comparator after using extracting on Object
#### Summary

Extend `usingComparatorForElementFieldsWithType` usage to `extracting` on `Object`
#### Example

``` java
Person joe = new Person("Joe", 25);
joe.setHeight(new BigDecimal("1.80"));

assertThat(joe).extracting("name", "height")
               .usingComparatorForElementFieldsWithType(new BigDecimalComparator(), BigDecimal.class)
               .containsExactly("Joe", new BigDecimal("1.8"));
```

### PR DESCRIPTION
**Pull request by fiery-phoenix**
#### Check List:
* Fixes #752 
* Unit tests : YES

### CODE REVIEW

**Comment by joel-costigliola** [comment]
thanks @fiery-phoenix, will review that after the 2.6.0/3.6.0 release that has priority.

**Comment by fiery-phoenix** [comment]
Is it needed to add `usingComparatorForType` to `AtomicReferenceArrayAssert`?

**Comment by joel-costigliola** [comment]
@fiery-phoenix ideally yes for `AtomicReferenceArrayAssert`, sorry for the late reply :crying_cat_face:

**Comment by fiery-phoenix** [comment]
Added `usingComparatorForType` to `AtomicReferenceArrayAssert`.

**Comment by joel-costigliola** [comment]
Integrated, many thanks @fiery-phoenix.

**Comment by fiery-phoenix** [comment]
you are welcome :)

**Pull request closed without merging**
