### PR TITLE
added biginteger to java6assertions

### PR DESCRIPTION
**Pull request by epeee**
It looks like I missed Java6*Assertions in the initial pr.

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
Strange. There are tests which compare the methods of the different assertion classes. I guess they buggy/incomplete as the missed this difference.

**Comment by joel-costigliola** [comment]
Thanks @epeee.

@PascalSchumacher there are no tests to synchronize `Assertions` with `Java6Assertions` as the latter is a subset of the former. There is no easy way (that I know of) to select the subset of `Assertions` `assertThat` methods to have in `Java6Assertions` (unless you can ask Java in which version a type was added).

**Comment by joel-costigliola** [comment]
FYI I have added tests to check that Java 6 assertions are in sync with Java 6 BDD and Soft assertions.

**Comment by PascalSchumacher** [comment]
Note to self: Do not post late at night, it makes one look stupid. Sorry for the noise.

**Pull request merged**
