### PR TITLE
Added isUpperCase/isLowerCase to String/CharSequence

### LINKED ISSUE #1106: Add `isUpperCase()` and `isLowerCase` to `AbstractCharSequenceAssert`
#### Summary

Add `isUpperCase()` and `isLowerCase` to `AbstractCharSequenceAssert`.
Just like `AbstractCharacterAssert ` also has these.

#### Example

```java
assertThat("ABC").isUpperCase(); // --> currently not possible

assertThat('A').isUpperCase(); // --> currently already possible
```

#### Java 8 specific ?

* YES : create Pull Request from the `master` branch
* NO  : create Pull Request from the `2.x` branch

### PR DESCRIPTION
**Pull request by marceloverdijk**
#### Check List:
* Fixes #1106
* Unit tests : YES
* Javadoc with a code example (API only) : YES

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
Thanks for the pull request 👍 

I think we should define what happens in edge cases.

With the current implementation of the pull request these assertions all pass:

```java
assertThat("").isUpperCase();
assertThat(" ").isUpperCase();
assertThat(".").isUpperCase();
assertThat("7").isUpperCase();
assertThat("A.7").isUpperCase();

assertThat("").isLowerCase();
assertThat(" ").isLowerCase();
assertThat(".").isLowerCase();
assertThat("7").isLowerCase();
assertThat("a.7").isLowerCase();
```

While these existing character assertions all fail:

```java
assertThat(' ').isUpperCase();
assertThat('.').isUpperCase();
assertThat('7').isUpperCase();

assertThat(' ').isLowerCase();
assertThat('.').isLowerCase();
assertThat('7').isLowerCase();
```

**Comment by marceloverdijk** [comment]
Good points @PascalSchumacher!
My implementation is quite simple using standard JDK `toUpperCase()`/`toLowerCase()` methods to compare. Maybe we should refine some edge cases indeed.

**Comment by joel-costigliola** [comment]
We should add all the edge cases in the javadoc code examples and states that it follows JDK `toUpperCase()`/`toLowerCase() so that it is crystal clear what the beahvior of the assertion is.

Thanks for the PR.

**Comment by joel-costigliola** [comment]
Integrated manually thanks @marceloverdijk.

**Pull request closed without merging**
