### PR TITLE
Add `isCompletedWithValueSatisfies` to `CompletableFuture` assertions

### PR DESCRIPTION
**Pull request by valery1707**
#### Check List:
* Relates to #1931 
* Unit tests: YES
* Javadoc with a code example (on API only): YES

### CODE REVIEW

**Comment by valery1707** [comment]
Do I need to add the same assertions into `AbstractFutureAssert`?
Do I need to add `@since` tag to JavaDoc? With which value?

**Comment by valery1707** [comment]
@joel-costigliola ping

**Comment by joel-costigliola** [comment]
@valery1707 will look at it shortly, thanks!

**Comment by valery1707** [comment]
@joel-costigliola ping

**Comment by joel-costigliola** [comment]
Will look at it for 3.18.0

**Comment by joel-costigliola** [comment]
Unless I'm mistaken, this is covered by [`succeedsWithin`](https://assertj.github.io/doc/#assertj-core-3.17.0-succeedsWithin). in https://github.com/joel-costigliola/assertj-core/pull/1930

**Pull request closed without merging**
