### PR TITLE
Add ignoring collection order to Recursive API

### LINKED ISSUE #1494: Support ignoring collection order in Recursive comparison API
It will be nice to be able to ignore collection order with Recursive comparison API.
Instead of writing something like:
```java
assertThat(actual).usingRecursiveComparison()
                  .ignoringFields("unorderedCollection")
                  .isEqualTo(expected);
assertThat(actual.getUnorderedCollection()).hasSameElementsAs(expected.getUnorderedCollection());
```
to have option to ignore collection order like this:
```java
assertThat(actual).usingRecursiveComparison()
                  .ignoringCollectionOrderInFields("unorderedCollection")
                  .isEqualTo(expected);
```

### PR DESCRIPTION
**Pull request by zeljko-mirovic**
Add ignoringCollectionOrderInFields() and ignoringCollectionOrderInFieldsMatchingRegexes() to Recursive API.

* Fixes #1494
* Unit tests : YES
* Javadoc with a code example (API only) : YES

### CODE REVIEW

**Comment by joel-costigliola** [comment]
thanks for the PR, I did look at it into details but it looks good.
I'm not going to integrate it quickly as I'm actually refactoring the recursive comparison (but 95% of your PR is relevant).

**Comment by joel-costigliola** [comment]
@zeljko-mirovic could you add the `ignoringCollectionOrder()` to the mix ?

**Comment by zeljko-mirovic** [comment]
> @zeljko-mirovic could you add the `ignoringCollectionOrder()` as a way to ignore collection order everywhere ?

Sure. I will do it next week.

**Comment by zeljko-mirovic** [comment]
ignoringCollectionOrder() added.

**Comment by joel-costigliola** [comment]
Integrated thanks @zeljko-mirovic for the good work!

**Pull request merged**
