### PR TITLE
fix a minor typo

### PR DESCRIPTION
**Pull request by epeee**

### CODE REVIEW

**Comment by joel-costigliola** [comment]
Good catch, thanks!

**Comment by joel-costigliola** [comment]
Hey @epeee,

Would you be interested in becoming an Assertj Core commiter ? (and possibly other assertj projects too if you are keen)

You have been contributing a lot and your contributions are of high quality, you also pay attention to details (often more than me !), I think you would be awesome as a commiter !

I haven't had as much time to give to assertj lately so it is a good time to expand the Assertj team.

Here's how we will work (and how we work with Pascal Schumacher who is oart of the team):
- no strings attached, if you have time to contribute, good, if not, no problem
- I want to be involved in any AssertJ API changes
- we discuss the main new features / improvements and AssertJ roadmap.
- we don't have to discuss all your contributions, especially the refactoring ones, but if you want my opinion feel free to ask
- if we disagree (which is ok), I'll have the final word, that's the advantage of being AssertJ benevolent dictator :)

I'm looking to hear what you think.
Cheers mate,

Joel

**Comment by epeee** [comment]
@joel-costigliola sure, I'd be interested. 

Ad 'how we will work': sounds good!

**Comment by joel-costigliola** [comment]
Awesome, welcome to the team!

**Pull request merged**
