### PR TITLE
Backport assertThatThrownBy() and catchThrowable() methods

### LINKED ISSUE #486: Backport assertThatThrownBy() to v1.x for Android
I am currently working on some Android code and wanted to use `assertThatThrownBy()` but realized that it wasn't available. Is v1.x still a valid target to allow its use with Android code? Would it make sense to backport that feature?

### PR DESCRIPTION
**Pull request by Turbo87**
resolves #486

### CODE REVIEW

**Comment by Turbo87** [comment]
@joel-costigliola any comments on this?

**Comment by joel-costigliola** [comment]
I was waiting for your feedback on https://github.com/joel-costigliola/assertj-core/issues/486#issuecomment-147978015, did I miss it ?

**Comment by Turbo87** [comment]
right, totally forgot about that. sorry!

I've tested it and written my feedback down in #500

**Comment by Turbo87** [comment]
looks like this is indeed not needed (see https://github.com/Turbo87/assertj-android-test/commit/5dad6177bb779fd1c2b2b2bb6088e51b54b8c34c)

**Comment by PascalSchumacher** [comment]
Indeed, I guess with https://github.com/joel-costigliola/assertj-core/commit/7881a570310e6904bd6eadddb5430c54f21e825e this can be closed.

**Pull request closed without merging**
