### PR TITLE
Sonarcloud ci master

### PR DESCRIPTION
**Pull request by btrajkovski**
#### Check List:
* Fixes: sonarcloud configuration
* Unit tests : NA
* Javadoc with a code example (API only) : Not needed

### CODE REVIEW

**Comment by joel-costigliola** [comment]
@btrajkovski thanks ! let's see if we have the sonar reports.

**Comment by joel-costigliola** [comment]
Hmmm still failing:
```
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.3.0.603:sonar (default-cli) on project assertj-core: Not authorized. Please check the properties sonar.login and sonar.password.
```

**Comment by joel-costigliola** [comment]
I have pushed another commit, making progress but still failing:
```
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.3.0.603:sonar (default-cli) on project assertj-core: Unable to load component class org.sonar.scanner.report.MetadataPublisher: Unable to load component class org.sonar.scanner.rule.ModuleQProfiles: Error 404 on https://sonarcloud.io/api/qualityprofiles/search.protobuf?projectKey=org.assertj%3Aassertj-core&organization=assertj : {"errors":[{"msg":"Component key 'org.assertj:assertj-core' not found"}]} -> [Help 1]```

**Comment by joel-costigliola** [comment]
Finally fixed after a bit of tinkering

**Comment by btrajkovski** [comment]
Very nice @joel-costigliola, I forgot to mention that token needs to be updated. 

Just as a note a few more things we can improve here:
1) Use encrypted token instead of plain sonarcloud token (https://docs.travis-ci.com/user/encryption-keys/). Right now everyone can use that token...
2) Check why code coverage is missing, previously it was working. I can take this one

**Comment by joel-costigliola** [comment]
1. 
I created an assertj organization, used an encrypted token but it did not work.
I can give it another shot ... 

2. that would be awesome, let's enable branch build for the PR in order to test that and once it works disable it to avoid having to push master to test if things work.

**Pull request merged**
