### PR TITLE
Allow return value of fail* methods to be ignored

### LINKED ISSUE #1298: Assertions.fail is causing problems due to @CheckReturnValue
#### Summary
It looks like `Assertions.fail` is no longer `void` starting from AssertJ 3.11.0 (#1294). Since `Assertions` is annotated with `@CheckReturnValue` quite some projects out there might run into troubles.

#### Example

```java
import org.assertj.core.api.Assertions;
import org.junit.Test;

public class AssertionsFailTest {

    @Test
    public void test() {
        Assertions.fail("failing this test on purpose");
    }
}

```

Using this example and errorprone every project which is using `Assertions.fail` will fail now with something like:

```
error: [CheckReturnValue] Ignored return value of method that is annotated with @CheckReturnValue
        Assertions.fail("failing this test on purpose");
```

### PR DESCRIPTION
**Pull request by gsheasby**
#### Check List:
* Fixes #1298
* Unit tests : NA
* Javadoc with a code example (API only) : NA

### CODE REVIEW

**Comment by filiphr** [comment]
@gsheasby you don't have to add the error prone dependency. You can just add `@CanIgnoreReturnValue` annotation next to `@CheckReturnValue` from AssertJ

**Comment by epeee** [comment]
Yes, indeed. I also would go for a new `@CanIgnoreReturnValue` annotation next to `org.assertj.core.util.CheckReturnValue`.

**Comment by gsheasby** [comment]
@filiphr @epeee sure, that makes sense.

I don't have time to contribute this today, but maybe next week.

**Comment by joel-costigliola** [comment]
I agree with @filiphr and @epeee, assertj has a policy of having no dependencies so we can't use `CanIgnoreReturnValue` from an external library

**Comment by epeee** [comment]
@gsheasby pls let me know if you are too busy right now to finish this pr. I can continue working on this one if so.

**Comment by joel-costigliola** [comment]
@epeee thanks!

**Comment by joel-costigliola** [comment]
fixed by #1310

**Pull request closed without merging**
