### PR TITLE
Fixes #1187: Exclude proxied class from SoftAssertions line number

### LINKED ISSUE #1187: Line number are not helpful for custom SoftAssertions declared outside of assertj package
#### Summary
SoftAssertions output errors including a stack trace element for each error message.
```The following assertion failed:
1) [error-message]
at [stack-trace-element]
2) [error-message]
at [stack-trace-element]
```
With assertj soft assertions this works great and the stack-trace-element allows to jumb directly into at the assertion call in the test class.
However when using a custom class soft assertions and this class is declared in a non assertj package e.g. "org.example.project.assertions" the stack-trace-element is from the ByteBuddy proxied assertion class.
So the output is something like
```
at MyProjectClassAssert$ByteBuddy$zSZUiQrB$auxiliary$7Qx1CRh1.call(MyProjectClassAssert$ByteBuddy$zSZUiQrB$auxiliary$7Qx1CRh1.java:-1)
```

#### Example

With the following assertion classes in package
```java
package org.example.project.assertions;
import java.util.Objects;
import org.assertj.core.api.AbstractAssert;
import org.assertj.core.api.SoftAssertions;

public class MyProjectSoftAssertions extends SoftAssertions {

  public static class MyProjectClass {
    private final Object value;
    public MyProjectClass(Object value) {
      this.value = value;
    }

    public Object getValue() {
      return value;
    }
  }

  public static class MyProjectClassAssert extends AbstractAssert<MyProjectClassAssert, MyProjectClass> {

    public MyProjectClassAssert(MyProjectClass actual) {
      super(actual, MyProjectClassAssert.class);
    }

    public MyProjectClassAssert hasValue(Object value) {
      if (!Objects.equals(actual.getValue(), value)) {
        failWithMessage("Expecting value to be <%s> but was <%s>:", value, actual.getValue());
      }
      return this;
    }
  }

  public MyProjectClassAssert assertThat(MyProjectClass actual) {
    return proxy(MyProjectClassAssert.class, MyProjectClass.class, actual);
  }
}
```

The following test code
```java
 @Test
  public void assertValue() {
    MyProjectSoftAssertions softly = new MyProjectSoftAssertions();
    softly.assertThat(new MyProjectClass("v2")).hasValue("v1");
    softly.assertAll();
  }
```
produces the following error message:
```
org.assertj.core.api.SoftAssertionError: 
The following assertion failed:
1) Expecting value to be <v1> but was <v2>:
at MyProjectSoftAssertions$MyProjectClassAssert$ByteBuddy$nP0a48xo$auxiliary$OKW4UxOl.call(MyProjectSoftAssertions$MyProjectClassAssert$ByteBuddy$nP0a48xo$auxiliary$OKW4UxOl.java:-1)
```

### PR DESCRIPTION
**Pull request by sarod**
#### Check List:
* Fixes #1187 
* Unit tests : YES 
* Javadoc with a code example (API only) : NA

### CODE REVIEW

**Comment by joel-costigliola** [comment]
Integrated thanks @sarod!

**Comment by joel-costigliola** [comment]
That's weird, the test fails [in Travis](https://travis-ci.org/joel-costigliola/assertj-core/builds/351639100) displaying a different stack trace, the error is reported in `MyProjectClassAssert` intead of `CustomSoftAssertionsLineNumberTest`.

I could not make the test fail on a local maven build or by adding the test in assertj-examples.

@sarod @PascalSchumacher any ideas why ? 

Don't spend too much time on this as the tests runs fine in eclipse (I haven't tested in Idea), I'm going to flag the with `@Ignore` in the meantime.

```
[ERROR] should_print_line_numbers_of_failed_assertions_even_if_custom_assertion_in_non_assertj_package(org.example.test.CustomSoftAssertionsLineNumberTest)  Time elapsed: 0.056 s  <<< FAILURE!
java.lang.AssertionError: 

Expecting:
 <"
The following assertion failed:
1) Expecting value to be <v2> but was <v1>:
at MyProjectClassAssert.hasValue(MyProjectClassAssert.java:27)
">
to contain:
 <"1) Expecting value to be <v2> but was <v1>:
at CustomSoftAssertionsLineNumberTest.should_print_line_numbers_of_failed_assertions_even_if_custom_assertion_in_non_assertj_package(CustomSoftAssertionsLineNumberTest.java:31)"> 
	at org.example.test.CustomSoftAssertionsLineNumberTest.should_print_line_numbers_of_failed_assertions_even_if_custom_assertion_in_non_assertj_package(CustomSoftAssertionsLineNumberTest.java:35)
```

**Comment by PascalSchumacher** [comment]
I disabled the removal of byte buddy classes and the test failure on travis displays:

```
CustomSoftAssertionsLineNumberTest.should_print_line_numbers_of_failed_assertions_even_if_custom_assertion_in_non_assertj_package:36 
Expecting:
 <"
The following assertion failed:
1) Expecting value to be <v2> but was <v1>:
at MyProjectClassAssert$ByteBuddy$kSex7yOE.failWithMessage$accessor$5zcOWebN(MyProjectClassAssert$ByteBuddy$kSex7yOE.java:-1)
">
to contain:
 <"1) Expecting value to be <v2> but was <v1>:
at CustomSoftAssertionsLineNumberTest.should_print_line_numbers_of_failed_assertions_even_if_custom_assertion_in_non_assertj_package(CustomSoftAssertionsLineNumberTest.java:32)">
```

I can replicate this locally when running `mvn clean test`.

**Comment by PascalSchumacher** [comment]
I printed the full stacktrace on `System.err` on travis:

```
java.lang.AssertionError: Expecting value to be <v2> but was <v1>:
	at org.assertj.core.api.AbstractAssert.failWithMessage(AbstractAssert.java:124)
	at org.example.test.MyProjectClassAssert$ByteBuddy$iMwbvLj2.failWithMessage$accessor$Io3ndTVz(Unknown Source)
	at org.example.test.MyProjectClassAssert$ByteBuddy$iMwbvLj2$auxiliary$hlGR1J2s.call(Unknown Source)
	at org.assertj.core.api.ErrorCollector.intercept(ErrorCollector.java:42)
	at org.example.test.MyProjectClassAssert$ByteBuddy$iMwbvLj2.failWithMessage(Unknown Source)
	at org.example.test.MyProjectClassAssert.hasValue(MyProjectClassAssert.java:27)
	at org.example.test.MyProjectClassAssert$ByteBuddy$iMwbvLj2.hasValue$accessor$Io3ndTVz(Unknown Source)
	at org.example.test.MyProjectClassAssert$ByteBuddy$iMwbvLj2$auxiliary$YG2yA2vQ.call(Unknown Source)
	at org.assertj.core.api.ErrorCollector.intercept(ErrorCollector.java:42)
	at org.example.test.MyProjectClassAssert$ByteBuddy$iMwbvLj2.hasValue(Unknown Source)
	at org.example.test.CustomSoftAssertionsLineNumberTest.should_print_line_numbers_of_failed_assertions_even_if_custom_assertion_in_non_assertj_package(CustomSoftAssertionsLineNumberTest.java:32)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:369)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:275)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:239)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:160)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
```

The first on assertj/byte-buddy entry is `at org.example.test.MyProjectClassAssert.hasValue(MyProjectClassAssert.java:27)`. Maybe we should add filtering for custom assert classes?

**Comment by joel-costigliola** [comment]
Maybe jacoco or sonar is instrumenting the test code and changes the stack trace ?

My local maven stack trace looks like:
```
[INFO] Running org.example.test.CustomSoftAssertionsLineNumberTest
java.lang.AssertionError: Expecting value to be <v2> but was <v1>:
	at org.example.test.MyProjectClassAssert$ByteBuddy$lL2yd3yS$auxiliary$ZByE9vTG.call(Unknown Source)
	at org.example.test.MyProjectClassAssert$ByteBuddy$lL2yd3yS$auxiliary$cpDqwnG8.call(Unknown Source)
	at org.example.test.CustomSoftAssertionsLineNumberTest.should_print_line_numbers_of_failed_assertions_even_if_custom_assertion_in_non_assertj_package(CustomSoftAssertionsLineNumberTest.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:369)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:275)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:239)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:160)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
```

**Comment by PascalSchumacher** [comment]
That was also my guess, but it worked with jacoco locally and sonar is not enabled for pull requests.

I changed the pull request to only execute `clean test`, but the stacktrace seems the same, see https://api.travis-ci.org/v3/job/351825750/log.txt

**Pull request closed without merging**
