### PR TITLE
Align WithAssertions and Assertions

### LINKED ISSUE #1005: [WithAssertions] ListAssert is broken due to generics fluff
#### Summary

#775 fixed some discrepancies between `WithAssertions` and `Assertions` (shipped in 3.6.0). Unfortunately,   I'm afraid that I got some generics wrong leading unwanted regression 😞 

#### Example

```java
public class RemoveMe implements WithAssertions {

  @Test
  public void fixme() {
    List<String> l = new ArrayList<>();
    assertThat(l).contains("foo");
  }
}
```

Is broken since 3.6.0.

```
Error:(213, 18) java: no suitable method found for contains(java.lang.String)
    method org.assertj.core.api.AbstractIterableAssert.contains(capture#3 of ? extends java.lang.String...) is not applicable
      (varargs mismatch; java.lang.String cannot be converted to capture#3 of ? extends java.lang.String)
    method org.assertj.core.api.ListAssert.contains(capture#3 of ? extends java.lang.String...) is not applicable
      (varargs mismatch; java.lang.String cannot be converted to capture#3 of ? extends java.lang.String)
```

This is related to the addition of the following method:

```
default <T> ListAssert<? extends T> assertThat(final List<? extends T> actual)
```

I think that return type should be `ListAssert<T>`, or `ListAssert<? super T>`, rather than `ListAssert<? extends T>`.    

Do you want me to open a PR to fix it? Should we review the API to spot such mistakes?

#### Java 8 specific ?

* YES : create Pull Request from the `master` branch

### PR DESCRIPTION
**Pull request by filiphr**
This PR aligns the `WithAssertions` and `Assertions`. Additionally tests are added that will make sure that we keep the API consistent, i.e. `WithAssertions` should have all methods that `Assertions` has.

#### Check List:
* Fixes #1005 
* Unit tests : YES
* Javadoc with a code example (API only) : NA

I was not sure if we need to add tests that make sure `WithAssertions` delegates the calls.

### CODE REVIEW

**Comment by filiphr** [comment]
What about the `@since` tags? Should we add those to the methods? If yes, should they be the same as in `Assertions` or `2.9.0 / 3.9.0`?

**Comment by joel-costigliola** [comment]
Put `2.9.0 / 3.9.0` in `WithAssertions` since they were not available before.

**Comment by filiphr** [comment]
I added only `@since 3.9.0`, because `WithAssertions` is present only in the master branch

**Comment by joel-costigliola** [comment]
in master, thanks !

**Pull request closed without merging**
