### PR TITLE
Fixes #1441 use raw string when given no arguments

### LINKED ISSUE #1441: UnknownFormatConversionException when asserting String with `%` sign
#### Summary
I have a test written in Kotlin. It throws `UnknownFormatConversionException` when I try to assert a String containing `%` character. The same test in Java works properly. 

  > A hint: Java test calls method `org.assertj.core.api.AbstractAssert#isEqualTo`, while Kotlin test calls `org.assertj.core.api.AbstractStringAssert#isEqualTo` (which is buggie when there is no args). 

#### Example

1. Test in Java - works:

```java
import org.junit.Test;
import static org.assertj.core.api.Assertions.assertThat;

public class AssertJTest {
  @Test
  public void assertJ12() {
    assertThat("foo %").isEqualTo("foo %");
  }
}
```

2. The same test in Kotlin - fails:

```kotlin
import org.assertj.core.api.Assertions.assertThat
import org.junit.Test

class AssertJTest {
  @Test
  fun assertJ12() {
    assertThat("foo %").isEqualTo("foo %")
  }
}
```

Failure message is:

```java
java.util.UnknownFormatConversionException: Conversion = '%'
	at java.base/java.util.Formatter.checkText(Formatter.java:2732)
	at java.base/java.util.Formatter.parse(Formatter.java:2718)
	at java.base/java.util.Formatter.format(Formatter.java:2655)
	at java.base/java.util.Formatter.format(Formatter.java:2609)
	at java.base/java.lang.String.format(String.java:2897)
	at org.assertj.core.api.AbstractStringAssert.isEqualTo(AbstractStringAssert.java:310)
	at controllers.api.AssertJTest.assertJ12(AssertJTest.kt:9)
```

### PR DESCRIPTION
**Pull request by asolntsev**
#### Check List:
* Fixes #1441
* Unit tests : YES
* Javadoc with a code example (API only) : NA

### CODE REVIEW

**Comment by asolntsev** [comment]
@joel-costigliola ping!

**Comment by joel-costigliola** [comment]
I'm in holidays ;-)

**Comment by asolntsev** [comment]
@joel-costigliola sure, no problems! Take you time. :)

P.S. It's probably a good idea to have few committers who can accept simple pull requests while you are on vacation?

**Comment by asolntsev** [comment]
I prepared alternative (probably better) PR for the same issue: https://github.com/joel-costigliola/assertj-core/pull/1465

**Comment by joel-costigliola** [comment]
Closing this one because of #1465

**Pull request closed without merging**
